services:
  - type: web
    name: dhun-server
    env: node
    rootDir: server
    buildCommand: |
      npm install &&
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o node_modules/youtube-dl-exec/bin/yt-dlp &&
      chmod +x node_modules/youtube-dl-exec/bin/yt-dlp &&
      node_modules/youtube-dl-exec/bin/yt-dlp --version
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGIN
        sync: false
    plan: free
